server:
  port: 8082

spring:
  application:
    name: eureka-client
  main:
    allow-bean-definition-overriding: true
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: true

logging:
  level:
    com:
      netflix:
        config:
          sources:
            URLConfigurationSource: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
